### ISSUE TITLE
VAC has been unable to perform anti-cheat checks on this user

### ISSUE THREAD

**Issue by ilyankin** [yourmnbbn/tiny-steam-client#2]
Hello, I've the following issue:
When I try to connect to the tiny-cg-server I've get "VAC has been unable to perform anti-cheat checks on this user" after about a minute.
Ports are open and Windows Firewall is disabled.
The server is public. I can find it in the steam servers list.

**Comment by ilyankin** [comment]
The problem is that I can't find my server on steam servers search(
I'll try to figure out what the problem is.

**Comment by yourmnbbn** [comment]
> When I try to connect to the tiny-cg-server I've get "VAC has been unable to perform anti-cheat checks on this user" after about a minute.

Don't start server with -vac option.

> The problem is that I can't find my server on steam servers search(

Don't forget to change the server region to yours.

**Comment by ilyankin** [comment]
@yourmnbbn, 

Thank you for you answer.

>Don't start server with -vac option.

Why?

>Don't forget to change the server region to yours.

I fixed it and it works with Asia server, why?

**Comment by ilyankin** [comment]
Are there any risks in these settings?

**Comment by yourmnbbn** [comment]
>Don't start server with -vac option.  Why?

Please see the [instruction](https://github.com/yourmnbbn/tiny-csgo-server#special-notice-if-youre-trying-to-use-tiny-steam-client).

>Don't forget to change the server region to yours. why?

By default the server is in Asia, other region has to manually [change the region setting](https://github.com/yourmnbbn/tiny-csgo-server#how-to-change-server-information).

>Are there any risks in these settings?

No.

**Comment by ilyankin** [comment]
@yourmnbbn,
I got you! Thanks a lot!
But I want to clarify something, how long does 1 round last in time?
And if you use SERVER_VAC_STATES = 1 is there still a chance of a drop?

**Comment by yourmnbbn** [comment]
Getting drops requires much more than that.

**Comment by ilyankin** [comment]
I read that enough any cs:go sever with VAC.

**Comment by yourmnbbn** [comment]
For more information about drops, add me in the discord Yourmnbbn#7367
